import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

import "./globals.css";
import Navbar from "@/components/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
  <body  >
        <Toaster position="top-center"/>
        <Navbar/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
